// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMpvCQ_Q6PyniiOCIQKYfdNy5a5WdTG38',
    appId: '1:148962352069:web:99b6221da51eef9cf2c9ac',
    messagingSenderId: '148962352069',
    projectId: 'whatsapp-43d84',
    authDomain: 'whatsapp-43d84.firebaseapp.com',
    storageBucket: 'whatsapp-43d84.appspot.com',
    measurementId: 'G-49JFF5MYF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqTZCQR1BQkHGhp_25-e60ANrN6dA_hkM',
    appId: '1:148962352069:android:3476280f713ea4e8f2c9ac',
    messagingSenderId: '148962352069',
    projectId: 'whatsapp-43d84',
    storageBucket: 'whatsapp-43d84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASB4uMtcew56OnVJzgCxLCh8Af10JplN0',
    appId: '1:148962352069:ios:318dcaaf04c1bf9cf2c9ac',
    messagingSenderId: '148962352069',
    projectId: 'whatsapp-43d84',
    storageBucket: 'whatsapp-43d84.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMpvCQ_Q6PyniiOCIQKYfdNy5a5WdTG38',
    appId: '1:148962352069:web:b7be7abc8141bf52f2c9ac',
    messagingSenderId: '148962352069',
    projectId: 'whatsapp-43d84',
    authDomain: 'whatsapp-43d84.firebaseapp.com',
    storageBucket: 'whatsapp-43d84.appspot.com',
    measurementId: 'G-W07490WY55',
  );
}
