name: whatsapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.2.1
  country_picker: ^2.0.26
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.3
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^2.0.0-dev.9
  image_picker: ^1.1.2
  photo_manager: ^3.2.3
  permission_handler: ^10.2.0


flutter_native_splash:
  color: "#ffffff"
  color_dark: "#111B21"
  image: assets/images/splash_light.png
  image_dark: assets/images/splash_light.png
  android_12:
    color: "#ffffff"
    color_dark: "#111B21"
    image: assets/images/splash_light.png
    image_dark: assets/images/splash_light.png
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#111B21"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

# To add assets to your application, add an assets section, like this:

  assets:
  - assets/images/circle.png